/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaceRouteImport } from './routes/race'
import { Route as QueueLabRouteImport } from './routes/queue-lab'
import { Route as BracketLabRouteImport } from './routes/bracket-lab'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RacerIndexRouteImport } from './routes/racer/index'
import { Route as RacerEventsEventIdRouteImport } from './routes/racer/events/$eventId'

const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueLabRoute = QueueLabRouteImport.update({
  id: '/queue-lab',
  path: '/queue-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketLabRoute = BracketLabRouteImport.update({
  id: '/bracket-lab',
  path: '/bracket-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacerIndexRoute = RacerIndexRouteImport.update({
  id: '/racer/',
  path: '/racer/',
  getParentRoute: () => rootRouteImport,
} as any)
const RacerEventsEventIdRoute = RacerEventsEventIdRouteImport.update({
  id: '/racer/events/$eventId',
  path: '/racer/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bracket-lab': typeof BracketLabRoute
  '/queue-lab': typeof QueueLabRoute
  '/race': typeof RaceRoute
  '/racer/': typeof RacerIndexRoute
  '/racer/events/$eventId': typeof RacerEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bracket-lab': typeof BracketLabRoute
  '/queue-lab': typeof QueueLabRoute
  '/race': typeof RaceRoute
  '/racer': typeof RacerIndexRoute
  '/racer/events/$eventId': typeof RacerEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bracket-lab': typeof BracketLabRoute
  '/queue-lab': typeof QueueLabRoute
  '/race': typeof RaceRoute
  '/racer/': typeof RacerIndexRoute
  '/racer/events/$eventId': typeof RacerEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bracket-lab'
    | '/queue-lab'
    | '/race'
    | '/racer/'
    | '/racer/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bracket-lab'
    | '/queue-lab'
    | '/race'
    | '/racer'
    | '/racer/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bracket-lab'
    | '/queue-lab'
    | '/race'
    | '/racer/'
    | '/racer/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BracketLabRoute: typeof BracketLabRoute
  QueueLabRoute: typeof QueueLabRoute
  RaceRoute: typeof RaceRoute
  RacerIndexRoute: typeof RacerIndexRoute
  RacerEventsEventIdRoute: typeof RacerEventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue-lab': {
      id: '/queue-lab'
      path: '/queue-lab'
      fullPath: '/queue-lab'
      preLoaderRoute: typeof QueueLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bracket-lab': {
      id: '/bracket-lab'
      path: '/bracket-lab'
      fullPath: '/bracket-lab'
      preLoaderRoute: typeof BracketLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racer/': {
      id: '/racer/'
      path: '/racer'
      fullPath: '/racer/'
      preLoaderRoute: typeof RacerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racer/events/$eventId': {
      id: '/racer/events/$eventId'
      path: '/racer/events/$eventId'
      fullPath: '/racer/events/$eventId'
      preLoaderRoute: typeof RacerEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BracketLabRoute: BracketLabRoute,
  QueueLabRoute: QueueLabRoute,
  RaceRoute: RaceRoute,
  RacerIndexRoute: RacerIndexRoute,
  RacerEventsEventIdRoute: RacerEventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
