import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { AppSnapshot } from "@roller-rumble/shared/types";
import { RollerRumbleApp } from "./app";
import {
  FIXED_NOW_MS,
  makeSnapshotDb,
  SCENARIO_COUNTDOWN_DURATION_MS,
  SCENARIO_OS2L,
  SCENARIO_PHOTO_BOOTH,
  SCENARIO_RESULT_PRESENTATION,
  SCENARIO_STRIPE,
  SCENARIO_TUNNEL
} from "./__fixtures__/snapshot-scenario";

/**
 * Golden wire-shape capture for the snapshot refactor.
 *
 * These fixtures are generated by the CURRENT, pre-extraction code paths:
 * `RollerRumbleApp.getSnapshot()` (full admin/projector shape) and the racer-payload
 * transform that lives in `server.ts`. The committed JSON files are the contract the
 * extracted `SnapshotAssembler` must reproduce byte-for-byte (see snapshot-assembler.test.ts).
 *
 * Verbatim copy of `createRacerSnapshotPayload` from server.ts:85-149 — kept here as the
 * oracle so the racer golden is captured from the legacy transform, not the new module.
 */
function legacyRacerSnapshotPayload(snapshot: AppSnapshot): AppSnapshot {
  const race = snapshot.raceProjection.race
    ? {
        ...snapshot.raceProjection.race,
        metrics: []
      }
    : null;

  return {
    ...snapshot,
    settings: {
      ...snapshot.settings,
      raceDisplayTickerMessages: []
    },
    raceProjection: {
      ...snapshot.raceProjection,
      race,
      metricsByRacerId: {},
      resultPresentation: null
    },
    themes: [],
    tunnel: {
      status: snapshot.tunnel.status,
      publicUrl: snapshot.tunnel.publicUrl ?? null
    },
    os2l: {
      enabled: snapshot.os2l.enabled,
      listening: false,
      advertising: false,
      port: snapshot.os2l.port,
      serviceName: snapshot.os2l.serviceName,
      armedRaceId: snapshot.os2l.armedRaceId,
      acceptedMessageCount: 0,
      ignoredMessageCount: 0,
      beatMessageCount: 0,
      lastBeatAt: null,
      lastRawMessage: null,
      lastRawMessageAt: null,
      lastAcceptedMessage: null,
      lastAcceptedAt: null,
      lastIgnoredMessage: null,
      lastIgnoredAt: null,
      lastIgnoredReason: null,
      lastError: null
    },
    photoBooth: {
      boothId: snapshot.photoBooth.boothId,
      status: snapshot.photoBooth.status,
      lastSeenAt: null,
      lastCaptureAt: null,
      pendingUploadCount: 0,
      message: null
    },
    paymentProvider: {
      stripe: {
        configured: snapshot.paymentProvider.stripe.configured,
        hasSecretKey: false,
        hasWebhookSecret: false,
        hasExtraCaCertFile: false,
        publicRacerUrl: null,
        message: ""
      }
    }
  };
}

/**
 * Build a target whose prototype is RollerRumbleApp so the real (pre-extraction)
 * getSnapshot + buildRacerSummaries + getCountdownDurationMs run, but whose live-state
 * dependencies are the deterministic scenario context. Mirrors app.test.ts conventions.
 */
function makeLegacyTarget(includeAllRaceData: boolean): RollerRumbleApp {
  const target = {
    db: makeSnapshotDb(includeAllRaceData),
    // reconcileQueueRaceStatuses is a DB write; the golden capture only needs it inert.
    reconcileQueueRaceStatuses: () => undefined,
    countdownRuntime: null,
    resultPresentation: SCENARIO_RESULT_PRESENTATION,
    tunnelManager: { getState: () => SCENARIO_TUNNEL },
    os2lTrigger: { getDiagnostics: () => SCENARIO_OS2L },
    getPhotoBoothStatus: () => SCENARIO_PHOTO_BOOTH,
    getStripeSetupStatus: () => SCENARIO_STRIPE,
    getCountdownDurationMs: () => SCENARIO_COUNTDOWN_DURATION_MS
  };
  Object.setPrototypeOf(target, RollerRumbleApp.prototype);
  return target as unknown as RollerRumbleApp;
}

describe("snapshot wire-shape golden (legacy capture)", () => {
  beforeEach(() => {
    vi.useFakeTimers();
    vi.setSystemTime(FIXED_NOW_MS);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("captures the full snapshot with includeAllRaceData enabled", async () => {
    const full = makeLegacyTarget(true).getSnapshot();
    await expect(JSON.stringify(full, null, 2)).toMatchFileSnapshot(
      "./__fixtures__/snapshot-full-all.json"
    );
  });

  it("captures the full snapshot with includeAllRaceData disabled", async () => {
    const full = makeLegacyTarget(false).getSnapshot();
    await expect(JSON.stringify(full, null, 2)).toMatchFileSnapshot(
      "./__fixtures__/snapshot-full-active-only.json"
    );
  });

  it("captures the racer-surface payload", async () => {
    const full = makeLegacyTarget(true).getSnapshot();
    const racer = legacyRacerSnapshotPayload(full);
    await expect(JSON.stringify(racer, null, 2)).toMatchFileSnapshot(
      "./__fixtures__/snapshot-racer.json"
    );
  });
});
